---

################################################################################
- name: Set needed vars for OKD
  ansible.builtin.set_fact:
    __openshift_install_url: "https://github.com/okd-project/okd/releases/download/{{ create_openshift_isos_openshift_version }}/openshift-install-linux-{{ create_openshift_isos_openshift_version }}.tar.gz"
    __coreos_installer_url: "https://mirror.openshift.com/pub/openshift-v4/clients/coreos-installer/latest/coreos-installer_amd64"
  tags:
    - always
