---

################################################################################
- name: Download OpenShift Installer from the internet
  ansible.builtin.get_url:
    url: "{{ __openshift_install_url }}"
    dest: "{{ __temp_folder }}/openshift-install-linux.tar.gz"
    mode: "0644"
  tags:
    - download
    - create_manifests
    - create_ignition
    - create_iso
################################################################################
- name: Extract OpenShift Installer tar file
  ansible.builtin.unarchive:
    src: "{{ __temp_folder }}/openshift-install-linux.tar.gz"
    dest: "{{ __temp_folder }}"
    include: openshift-install
    remote_src: true
  tags:
    - download
    - create_manifests
    - create_ignition
    - create_iso
################################################################################
- name: Make sure OpenShift Installer is executable
  ansible.builtin.file:
    path: "{{ __temp_folder }}/openshift-install"
    mode: "755"
  tags:
    - download
    - create_manifests
    - create_ignition
    - create_iso
################################################################################
# - name: Cleanup OpenShift Installer tar file
#   ansible.builtin.file:
#     path: "{{ __temp_folder }}/openshift-install-linux.tar.gz"
#     state: absent
#   tags:
#     - download
#     - create_manifests
#     - create_ignition
#     - create_iso
################################################################################
- name: Download CoreOS Installer from the internet
  ansible.builtin.get_url:
    url: "{{ __coreos_installer_url }}"
    dest: "{{ __temp_folder }}/coreos-installer"
    mode: "755"
  tags:
    - download
    - create_iso
    - bootstrap
    - control_plane
    - master
    - compute
    - worker
    - embed_ignition
    - embed_static_ip
