---

################################################################################
- name: Create vars file from template
  ansible.builtin.template:
    src: vars-control-plane.yml.j2
    dest: "{{ __temp_folder }}/vars-control-plane.yml"
    mode: "0644"
  tags:
    - always
################################################################################
- name: Include template vars file
  ansible.builtin.include_vars: "{{ __temp_folder }}/vars-control-plane.yml"
  tags:
    - always
################################################################################
- name: Create initial ISO for each control plane node
  ansible.builtin.copy:
    src: "{{ __temp_folder }}/{{ __iso_filename }}"
    dest: "{{ __temp_folder }}/{{ __full_cluster_name }}/isos/{{ item['iso_filename'] }}"
    remote_src: true
    mode: "0644"
  loop: "{{ __control_plane_nodes }}"
  loop_control:
    label: "{{ item['iso_filename'] }}"
  tags:
    - control_plane
    - master
    - create_iso
################################################################################
- name: Embed ignition file in each ISO
  ansible.builtin.command: >-
    ./coreos-installer iso ignition embed -fi ./{{ __full_cluster_name }}/{{ item['ign_filename'] }}
    {{ __full_cluster_name }}/isos/{{ item['iso_filename'] }}
  args:
    chdir: "{{ __temp_folder }}"
  loop: "{{ __control_plane_nodes }}"
  loop_control:
    label: "{{ item['iso_filename'] }}"
  register: __embed_ignition
  changed_when: __embed_ignition.rc == 0 and __embed_ignition.stderr == ""
  tags:
    - control_plane
    - master
    - embed_ignition
################################################################################
- name: Embed static IP information in each ISO
  ansible.builtin.command: >-
    ./coreos-installer iso kargs modify -a "{{ item[1] }}" \
    {{ __full_cluster_name }}/isos/{{ item[0]['iso_filename'] }}
  args:
    chdir: "{{ __temp_folder }}"
  with_subelements:
    - "{{ __control_plane_nodes }}"
    - kargs
  loop_control:
    label: "{{ item[0]['iso_filename'] }} -=> {{ item[1] }}"
  register: __embed_static_ip
  changed_when: __embed_static_ip.rc == 0 and __embed_static_ip.stderr == ""
  tags:
    - control_plane
    - master
    - embed_static_ip
################################################################################

