---

################################################################################
- name: Add needed vars for each control plane node
  ansible.builtin.set_fact:
    __control_plane_nodes: >-
      {{ __control_plane_nodes | default([]) + [item |
      combine({'hostname': item['name'] | lower + '-' + create_openshift_isos_base_domain | lower,
      'iso_filename': 'master-' + item['name'] + '.iso',
      'ign_filename': 'master.ign'})] }}
  loop: "{{ create_openshift_isos_control_plane_nodes }}"
  loop_control:
    label: "{{ item['name'] }}"
  when: create_openshift_isos_control_plane_nodes | length > 1
################################################################################
- name: Add needed vars for single node
  ansible.builtin.set_fact:
    __control_plane_nodes: >-
      {{ __control_plane_nodes | default([]) + [item |
      combine({'hostname': item['name'] | lower + '-' + create_openshift_isos_base_domain | lower,
      'iso_filename': 'single-node-' + item['name'] + '.iso',
      'ign_filename': 'bootstrap-in-place-for-live-iso.ign'})] }}
  loop: "{{ create_openshift_isos_control_plane_nodes }}"
  loop_control:
    label: "{{ item['name'] }}"
  when: create_openshift_isos_control_plane_nodes | length == 1
################################################################################
- name: Update create_openshift_isos_control_plane_nodes fact
  ansible.builtin.set_fact:
    create_openshift_isos_control_plane_nodes: "{{ __control_plane_nodes }}"
    __control_plane_nodes: []
################################################################################
- name: Add iso_kargs to each control plane node as needed
  ansible.builtin.set_fact:
    __control_plane_nodes: >-
      {{ __control_plane_nodes | default([]) + [item |
      combine({'iso_kargs': 'ip=' + item['ip'] + '::' + item['gateway'] + ':' + item['netmask'] + ':' + item['hostname'] + ':' + item['interface'] + ':off:' + item['nameserver']})] }}
  loop: "{{ create_openshift_isos_control_plane_nodes }}"
  loop_control:
    label: "{{ item['name'] }}"
  when:
    - item['ip'] is defined
    - item['gateway'] is defined
    - item['netmask'] is defined
    - item['hostname'] is defined
    - item['interface'] is defined
    - item['nameserver'] is defined
################################################################################
- name: Update create_openshift_isos_control_plane_nodes fact
  ansible.builtin.set_fact:
    create_openshift_isos_control_plane_nodes: "{{ __control_plane_nodes }}"
    __control_plane_nodes: []
################################################################################
- name: Create initial ISO for each control plane node
  ansible.builtin.copy:
    src: "{{ __temp_folder }}/{{ __iso_filename }}"
    dest: "{{ __temp_folder }}/{{ __full_cluster_name }}/isos/{{ item['iso_filename'] }}"
    remote_src: true
    mode: "0644"
  loop: "{{ create_openshift_isos_control_plane_nodes }}"
  loop_control:
    label: "{{ item['iso_filename'] }}"
###############################################################################
- name: Embed ignition file in each ISO
  ansible.builtin.command: >-
    ./coreos-installer iso ignition embed -fi ./{{ __full_cluster_name }}/{{ item['ign_filename'] }}
    {{ __full_cluster_name }}/isos/{{ item['iso_filename'] }}
  args:
    chdir: "{{ __temp_folder }}"
  loop: "{{ create_openshift_isos_control_plane_nodes }}"
  loop_control:
    label: "{{ item['iso_filename'] }}"
  register: __embed_ignition
  changed_when: __embed_ignition.rc == 0 and __embed_ignition.stderr == ""
################################################################################
- name: Embed static IP information in each ISO
  ansible.builtin.command: >-
    ./coreos-installer iso kargs modify -a "{{ item['iso_kargs'] }}" \
    {{ __full_cluster_name }}/isos/{{ item['iso_filename'] }}
  args:
    chdir: "{{ __temp_folder }}"
  loop: "{{ create_openshift_isos_control_plane_nodes }}"
  loop_control:
    label: "{{ item['iso_filename'] }}"
  register: __embed_static_ip
  changed_when: __embed_static_ip.rc == 0 and __embed_static_ip.stderr == ""
  when: item['iso_kargs'] is defined
################################################################################
