---

################################################################################
- name: Run openshift-install command to get Manifest files
  ansible.builtin.command: "./openshift-install --dir={{ __full_cluster_name }} create manifests"
  args:
    chdir: "{{ playbook_dir }}/temp"
  changed_when: false
  register: __openshift_manifests
  when: control_plane_nodes | length > 1
################################################################################
- name: Set create_param based on number of control plane nodes
  ansible.builtin.set_fact:
    __create_param: "{% if create_openshift_isos_control_plane_nodes | length == 1 %}single-node-ignition-config{% else %}ignition-configs{% endif %}"
################################################################################
- name: Run openshift-install command to get Ignition files
  ansible.builtin.command: "./openshift-install --dir={{ __full_cluster_name }} create {{ __create_param }}"
  args:
    chdir: "{{ __temp_folder }}"
  changed_when: false
  register: __openshift_ignition
